import CssBaseline from '@mui/material/CssBaseline';
import { Inter } from 'next/font/google';
// import { ThemeProvider } from "@/context/ThemeContext";
import { getServerSession } from 'next-auth';

import Footer from '@/components/Footer';
import Navbar from '@/components/Navbar';
import AuthProvider from '@/lib/SessionProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Maps',
    description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
    const session = await getServerSession();

    return (
        <>
            {/* <Navbar /> */}
            {children}
            <div style={{ zIndex: 10, position: 'relative' }}>{/* <Footer /> */}</div>
        </>
    );
}
