import { Inter } from 'next/font/google';
import { getServerSession } from 'next-auth';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Maps',
    description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
    await getServerSession();
    return (
        <>
            <div className={inter.className}> {/* Apply the font class */}
                {children}
            </div>
            <div style={{ zIndex: 10, position: 'relative' }}>
                {/* <Footer /> */}
            </div>
        </>
    );
}
