import CssBaseline from '@mui/material/CssBaseline';
import { Inter } from 'next/font/google';
// import { ThemeProvider } from "@/context/ThemeContext";
import { getServerSession } from 'next-auth';

import AuthProvider from '@/lib/SessionProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Maps',
    description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
    const session = await getServerSession();

    return (
        <div
            style={{
                minHeight: '100vh',
                padding: '1rem 0',
                backgroundImage: 'linear-gradient(to top, #e6e9f0 0%, #eef1f5 100%)',
            }}
        >
            {children}
        </div>
    );
}
