export const metadata = {
  title: 'Maps',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {

  return (
    <div
      style={{
        minHeight: '100vh',
        padding: '1rem 0',
        backgroundImage: 'linear-gradient(to top, #e6e9f0 0%, #eef1f5 100%)',
      }}
    >
      {children}
    </div>
  );
}
